### ISSUE TITLE
User Story 3: As a user, I want to see a motivational quote each day on the home page so that I stay motivated to complete my tasks

### ISSUE THREAD

**Issue by reesegreen2014** [reesegreen2014/TaskPro#6]
### Acceptance Criteria:

- [x] A motivational quote is fetched from an external API.
- [x] The quote is displayed prominently on the home page.
- [x] The quote updates with a random quote each time the home page is reloaded.
